/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// 2. Precache all assets generated by Vite

precacheAndRoute(self.__WB_MANIFEST)

// 3. Take control immediately
self.skipWaiting()
clientsClaim()

// 4. Firebase Messaging Service Worker
import { initializeApp } from "firebase/app";
import { getMessaging, onBackgroundMessage } from "firebase/messaging/sw";

import { firebaseConfig } from './config';

// Initialize Firebase in SW
const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

// Handle background messages
onBackgroundMessage(messaging, (payload) => {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    // Custom notification logic if needed, but SDK handles basic display automatically
    // Removing manual showNotification to prevent double notifications (SDK + Manual)
    const notificationTitle = payload.notification?.title || 'Salone Pacer Notification';
    const notificationOptions = {
        body: payload.notification?.body,
        icon: '/pwa-192x192.png'
    };
    self.registration.showNotification(notificationTitle, notificationOptions);
});

console.log('Service Worker (with Firebase) is running!')
