/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

// 1. Clean up old caches
cleanupOutdatedCaches()

// 2. Precache all assets generated by Vite
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST)

// 3. Take control immediately
self.skipWaiting()
clientsClaim()

// 4. Firebase Messaging Service Worker
import { initializeApp } from "firebase/app";
import { getMessaging, onBackgroundMessage } from "firebase/messaging/sw";

const firebaseConfig = {
    apiKey: "AIzaSyChbBQnMB3sBggkMC2LerQD1DY4CUAHBv8",
    authDomain: "salon-pacer-app.firebaseapp.com",
    projectId: "salon-pacer-app",
    storageBucket: "salon-pacer-app.firebasestorage.app",
    messagingSenderId: "859913575834",
    appId: "1:859913575834:web:5843dd0131839c60cf2e23"
};

// Initialize Firebase in SW
const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

// Handle background messages
onBackgroundMessage(messaging, (payload) => {
    console.log('[firebase-messaging-sw.js] Received background message ', payload);
    // Custom notification logic if needed, but SDK handles basic display automatically
    const notificationTitle = payload.notification?.title || 'Notification';
    const notificationOptions = {
        body: payload.notification?.body,
        icon: '/pwa-192x192.png'
    };

    self.registration.showNotification(notificationTitle, notificationOptions);
});

console.log('Service Worker (with Firebase) is running!')
