/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// 2. Precache all assets generated by Vite

precacheAndRoute(self.__WB_MANIFEST)

// 3. Take control immediately
self.skipWaiting()
clientsClaim()
